apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: black-hole
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: yunusde/black-hole
          ports:
            - containerPort: 8080
